apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workflow-dummy-ui-ingress
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
spec:
  tls:
    - hosts:
        - "{{ .Values.hostname }}"
  rules:
    - host: "{{ .Values.hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: workflow-dummy-ui
                port:
                  number: 80
